<?php

namespace OctaconDeveloper\LaravelNaijaFaker\Factory;

class LocalGovernment extends \OctaconDeveloper\LaravelNaijaFaker\Load
{

    protected static $States = array(
        'NG-EK' => 'Ekiti',
        'NG-LA' => 'Lagos',
        'NG-OG' => 'Ogun',
        'NG-ON' => 'Ondo',
        'NG-OS' => 'Osun',
        'NG-OY' => 'Oyo',
        'NG-BE' => 'Benue',
        'NG-KO' => 'Kogi',
        'NG-KW' => 'Kwara',
        'NG-NA' => 'Nasarawa',
        'NG-NI' => 'Niger',
        'NG-PL' => 'Plateau',
        'NG-FCT' => 'FCT Abuja',
        'NG-AD' => 'Adamawa',
        'NG-BA' => 'Bauchi',
        'NG-BO' => 'Borno',
        'NG-GO' => 'Gombe',
        'NG-TA' => 'Taraba',
        'NG-YO' => 'Yobe',
        'NG-JI' => 'Jigawa',
        'NG-KD' => 'Kaduna',
        'NG-KN' => 'Kano',
        'NG-KT' => 'Katsina',
        'NG-KE' => 'Kebbi',
        'NG-SO' => 'Sokoto',
        'NG-ZA' => 'Zamfara',
        'NG-AB' => 'Abia',
        'NG-AN' => 'Anambra',
        'NG-EB' => 'Ebonyi',
        'NG-EN' => 'Enugu',
        'NG-IM' => 'Imo',
        'NG-AK' => 'Akwa Ibom',
        'NG-BY' => 'Bayelsa',
        'NG-CR' => 'Cross River',
        'NG-RI' => 'Rivers',
        'NG-DE' => 'Delta',
        'NG-ED' => 'Edo'
    );

    protected static $abiaState = array(
        'Aba North',
        'Aba South',
        'Arochukwu',
        'Bende',
        'Ikwuano',
        'Isiala Ngwa North',
        'Isiala Ngwa South',
        'Isuikwuato',
        'Obi Ngwa',
        'Ohafia',
        'Osisioma Ngwa',
        'Ugwunagbo',
        'Ukwa East',
        'Ukwa West',
        'Umuahia North',
        'Umuahia South',
        'Umu Nneochi'
    );

    protected static $adamawaState = array(
        'Demsa',
        'Fufore',
        'Ganye',
        'Girei',
        'Gombi',
        'Guyuk',
        'Hong',
        'Jada',
        'Lamurde',
        'Madagali',
        'Maiha',
        'Mayo-Belwa',
        'Michika',
        'Mubi North',
        'Mubi South',
        'Numan',
        'Shelleng',
        'Song',
        'Toungo',
        'Yola',
        'Jimeta'
    );

    protected static $akwaIbomState = array(
        'Abak',
        'Eastern Obolo',
        'Eket',
        'Esit-Eket',
        'Essien Udim',
        'Etim-Ekpo',
        'Etinan',
        'Ibeno',
        'Ibesikpo-Asutan',
        'Ibiono-Ibom',
        'Ika',
        'Ikono',
        'Ikot Abasi',
        'Ikot Ekpene',
        'Ini',
        'Itu',
        'Mbo',
        'Mkpat-Enin',
       ' Nsit-Atai',
        'Nsit-Ibom',
        'Nsit-Ubium',
        'Obot-Akara',
        'Okobo',
        'Onna',
        'Oron',
        'Oruk Anam',
        'Ukanafun',
        'Udung-Uko',
        'Uruan',
       ' Urue-Offong/Oruko',
        'Uyo'
    );

    protected static $anambraState = array(
        'Aguata',
        'Awka North',
        'Awka South',
        'Anambra East',
        'Anambra West',
        'Anaocha',
        'Ayamelum',
        'Dunukofia',
        'Ekwusigo',
        'Idemili North',
        'Idemili South',
        'Ihiala',
        'Njikoka',
        'Nnewi North',
        'Nnewi South',
        'Ogbaru',
        'Onitsha North',
        'Onitsha South',
        'Orumba North',
        'Orumba South',
        'Oyi'
    );

    protected static $bauchiState = array(
        'Bauchi',
        'Tafawa Balewa',
        'Dass',
        'Toro',
        'Bogoro',
        'Ningi',
        'Warji',
        'Ganjuwa',
        'Kirfi',
        'Alkaleri',
        'Darazo',
        'Misau',
        'Giade',
        'Shira',
        "Jama\'are",
        'Katagum',
        'Itas/Gadau',
        'Zaki',
        'Gamawa',
        'Damban'
    );

    protected static $bayelsaState = array(
        'Brass',
        'Ekeremor',
        'Kolokuma/Opokuma',
        'Nembe',
        'Ogbia',
        'Sagbama',
        'Southern Ijaw',
        'Yenagoa'
    );

    protected static $benueState = array(
        'Ado',
        'Agatu',
        'Apa',
        'Buruku',
        'Gboko',
        'Guma',
        'Gwer East',
        'Gwer West',
        'Katsina-Ala',
        'Konshisha',
        'Kwande',
        'Logo',
        'Makurdi',
        'Obi',
        'Ogbadibo',
        'Ohimini',
        'Oju',
        'Okpokwu',
        'Otukpo',
        'Tarka',
        'Ukum',
        'Ushongo',
        'Vandeikya'
    );

    protected static $bornoState = array(
        'Abadam',
        'Askira/Uba',
        'Bama',
        'Bayo',
        'Biu',
        'Chibok',
        'Damboa',
        'Dikwa',
        'Gubio',
        'Guzamala',
        'Gwoza',
        'Hawul',
        'Jere',
        'Kaga',
        'Kala/Balge',
        'Konduga',
        'Kukawa',
        'Kwaya Kusar',
        'Mafa',
        'Magumeri',
        'Maiduguri',
        'Marte',
        'Mobbar',
        'Monguno',
        'Ngala',
        'Nganzai',
        'Shani' ,
    );

    protected static $crossRiverState = array(
        'Akpabuyo',
        'Odukpani',
        'Akamkpa',
        'Biase',
        'Abi',
        'Ikom',
        'Yarkur',
        'Odubra',
        'Boki',
        'Ogoja',
        'Yala',
        'Obanliku',
        'Obudu',
        'Calabar South',
        'Etung',
        'Bekwara',
        'Bakassi',
        'Calabar Municipality'
    );

    protected static $deltaState = array(
        'Asaba',
        'Oshimili',
        'Aniocha',
        'Aniocha South',
        'Ika South',
        'Ika North-East',
        'Ndokwa West',
        'Ndokwa East',
        'Isoko south',
        'Isoko North',
        'Bomadi',
        'Burutu',
        'Ughelli South',
        'Ughelli North',
        'Ethiope West',
        'Ethiope East',
        'Sapele',
        'Okpe',
        'Warri North',
        'Warri South',
        'Uvwie',
        'Udu',
        'Warri Central',
        'Ukwani',
        'Oshimili North',
        'Patani'
    );

    protected static $ebonyiState = array(
        'Afikpo South',
        'Afikpo North',
        'Onicha',
        'Ohaozara',
        'Abakaliki',
        'Ishielu',
        'lkwo',
        'Ezza',
        'Ezza South',
        'Ohaukwu',
        'Ebonyi',
        'Ivo',
    );

    protected static $edoState = array(
        'Benin City',
        'Esan North-East',
        'Esan Central',
        'Esan West',
        'Egor',
        'Ukpoba',
        'Central',
        'Etsako Central',
        'Igueben',
        'Oredo',
        'Ovia SouthWest',
        'Ovia South-East',
        'Orhionwon',
        'Uhunmwonde',
        'Etsako East',
        'Esan South-East',
    );

    protected static $ekitiState =  array(
        'Ado Ekiti',
        'Ekiti-East',
        'Ekiti-West',
        'Emure/Ise/Orun',
        'Ekiti South-West',
        'Ikare',
        'Irepodun',
        'Ijero',
        'Ido/Osi',
        'Oye',
        'Ikole',
        'Moba',
        'Gbonyin',
        'Efon',
        'Ise/Orun',
        'Ilejemeje',
    );

    protected static $enuguState = array(
        'Enugu South',
        'Igbo-Eze South',
        'Enugu North',
        'Nkanu',
        'Udi Agwu',
        'Oji-River',
        'Ezeagu',
        'IgboEze North',
        'Isi-Uzo',
        'Nsukka',
        'Igbo-Ekiti',
        'Uzo-Uwani',
        'Enugu East',
        'Aninri',
        'Nkanu East',
        'Udenu'
    );

    protected static $gombeState = array(
        'Akko',
        'Balanga',
        'Billiri',
        'Dukku',
        'Kaltungo',
        'Kwami',
        'Shomgom',
        'Funakaye',
        'Gombe',
        'Nafada/Bajoga',
        'Yamaltu/Delta'
    );

    protected static $imoState = array(
        'Aboh-Mbaise',
        'Ahiazu-Mbaise',
        'Ehime-Mbano',
        'Ezinihitte',
        'Ideato North',
        'Ideato South',
        'Ihitte/Uboma',
        'Ikeduru',
        'Isiala Mbano',
        'Isu',
        'Mbaitoli',
        'Ngor-Okpala',
        'Njaba',
        'Nwangele',
        'Nkwerre',
        'Obowo',
        'Oguta',
        'Ohaji/Egbema',
        'Okigwe',
        'Orlu',
        'Orsu',
        'Oru East',
        'Oru West',
        'Owerri-Municipal',
        'Owerri North',
        'Owerri West'
    );

    protected static $jigawaState = array(
        'Auyo',
        'Babura',
        'Birni Kudu',
        'Biriniwa',
        'Buji',
        'Dutse',
        'Gagarawa',
        'Garki',
        'Gumel',
        'Guri',
        'Gwaram',
        'Gwiwa',
        'Hadejia',
        'Jahun',
        'Kafin Hausa',
        'Kaugama Kazaure',
        'Kiri Kasamma',
        'Kiyawa',
        'Maigatari',
        'Malam Madori',
        'Miga',
        'Ringim',
        'Roni',
        'Sule-Tankarkar',
        'Taura',
        'Yankwashi',
    );

    protected static $kadunaState = array(
        'Birni-Gwari',
        'Chikun',
        'Giwa',
        'Igabi',
        'Ikara',
        'jaba',
        'Jema\'a',
        'Kachia',
        'Kaduna North',
        'Kaduna South',
        'Kagarko',
        'Kajuru',
        'Kaura',
        'Kauru',
        'Kubau',
        'Kudan',
        'Lere',
        'Makarfi',
        'Sabon-Gari',
        'Sanga',
        'Soba',
        'Zango-Kataf',
        'Zaria',
    );

    protected static $kanoState = array (
        'Ajingi',
        'Albasu',
        'Bagwai',
        'Bebeji',
        'Bichi',
        'Bunkure',
        'Dala',
        'Dambatta',
        'Dawakin Kudu',
        'Dawakin Tofa',
        'Doguwa',
        'Fagge',
        'Gabasawa',
        'Garko',
        'Garum',
        'Mallam',
        'Gaya',
        'Gezawa',
        'Gwale',
        'Gwarzo',
        'Kabo',
        'Kano Municipal',
        'Karaye',
        'Kibiya',
        'Kiru',
        'kumbotso',
        'Kunchi',
        'Kura',
        'Madobi',
        'Makoda',
        'Minjibir',
        'Nasarawa',
        'Rano',
        'Rimin Gado',
        'Rogo',
        'Shanono',
        'Sumaila',
        'Takali',
        'Tarauni',
        'Tofa',
        'Tsanyawa',
        'Tudun Wada',
        'Ungogo',
        'Warawa',
        'Wudil'
    );

    protected static $katsinaState = array(
        'Bakori',
        'Batagarawa',
        'Batsari',
        'Baure',
        'Bindawa',
        'Charanchi',
        'Dandume',
        'Danja',
        'Dan Musa',
        'Daura',
        'Dutsi',
        'Dutsin-Ma',
        'Faskari',
        'Funtua',
        'Ingawa',
        'Jibia',
        'Kafur',
        'Kaita',
        'Kankara',
        'Kankia',
        'Katsina',
        'Kurfi',
        'Kusada',
        'Mai\'Adua',
        'Malumfashi',
        'Mani',
        'Mashi',
        'Matazuu',
        'Musawa',
        'Rimi',
        'Sabuwa',
        'Safana',
        'Sandamu',
        'Zango'
    );

    protected static $kebbiState = array(
        'Aleiro',
        'Arewa-Dandi',
        'Argungu',
        'Augie',
        'Bagudo',
        'Birnin Kebbi',
        'Bunza',
        'Dandi' ,
        'Fakai',
        'Gwandu',
        'Jega',
        'Kalgo' ,
        'Koko/Besse',
        'Maiyama',
        'Ngaski',
        'Sakaba',
        'Shanga',
        'Suru',
        'Wasagu/Danko',
        'Yauri',
        'Zuru',
    );

    protected static $kogiState = array(
        'Adavi',
        'Ajaokuta',
        'Ankpa',
        'Bassa',
        'Dekina',
        'Ibaji',
        'Idah',
        'Igalamela-Odolu',
        'Ijumu',
        'Kabba/Bunu',
        'Kogi',
        'Lokoja',
        'Mopa-Muro',
        'Ofu',
        'Ogori/Mangongo',
        'Okehi',
        'Okene',
        'Olamabolo',
        'Omala',
        'Yagba East',
        'Yagba West',
    );

    protected static $kwaraState = array(
        'Asa',
        'Baruten',
        'Edu',
        'Ekiti',
        'Ifelodun',
        'Ilorin East',
        'Ilorin West',
        'Irepodun',
        'Isin',
        'Kaiama',
        'Moro',
        'Offa',
        'Oke-Ero',
        'Oyun',
        'Pategi'
    );

    protected static $lagosState = array(
        'Agege',
        'Ajeromi-Ifelodun',
        'Alimosho',
        'Amuwo-Odofin',
        'Apapa',
        'Badagry',
        'Epe',
        'Eti-Osa',
        'Ibeju/Lekki',
        'Ifako-Ijaye',
        'Ikeja',
        'Ikorodu',
        'Kosofe',
        'Lagos Island',
        'Lagos Mainland',
        'Mushin',
        'Ojo',
        'Oshodi-Isolo',
        'Shomolu',
        'Surulere'
    );

    protected static $nasarawaState = array(
        'Akwanga',
        'Awe',
        'Doma',
        'Karu',
        'Keana',
        'Keffi',
        'Kokona',
        'Lafia',
        'Nasarawa',
        'Nasarawa-Eggon',
        'Obi',
        'Toto',
        'Wamba'
    );

    protected static $nigerState = array(
        'Agaie',
        'Agwara',
        'Bida',
        'Borgu',
        'Bosso',
        'Chanchaga',
        'Edati',
        'Gbako',
        'Gurara',
        'Katcha',
        'Kontagora',
        'Lapai',
        'Lavun',
        'Magama',
        'Mariga',
        'Mashegu',
        'Mokwa',
        'Muya',
        'Pailoro',
        'Rafi',
        'Rijau',
        'Shiroro',
        'Suleja',
        'Tafa',
        'Wushishi'
    );

    protected static $ogunState = array(
        'Abeokuta North',
        'Abeokuta South',
        'Ado-Odo/Ota',
        'Egbado North',
        'Egbado South',
        'Ewekoro',
        'Ifo',
        'Ijebu East',
        'Ijebu North',
        'Ijebu North East',
        'Ijebu Ode',
        'Ikenne',
        'Imeko-Afon',
        'Ipokia',
        'Obafemi-Owode',
        'Ogun Waterside',
        'Odeda',
        'Odogbolu',
        'Remo North',
        'Shagamu'
    );

    protected static $ondoState = array(
        'Akoko North East',
        'Akoko North West',
        'Akoko South East',
        'Akoko South West',
        'Akure North',
        'Akure South',
        'Ese-Odo',
        'Idanre',
        'Ifedore',
        'Ilaje',
        'Ile-Oluji',
        'Okeigbo',
        'Irele',
        'Odigbo',
        'Okitipupa',
        'Ondo East',
        'Ondo West',
        'Ose',
        'Owo'
    );

    protected static $osunState = array(
        'Aiyedade',
        'Aiyedire',
        'Atakumosa East',
        'Atakumosa West',
        'Boluwaduro',
        'Boripe',
        'Ede North',
        'Ede South',
        'Egbedore',
        'Ejigbo',
        'Ife Central',
        'Ife East',
        'Ife North',
        'Ife South',
        'Ifedayo',
        'Ifelodun',
        'Ila',
        'Ilesha East',
        'Ilesha West',
        'Irepodun',
        'Irewole',
        'Isokan',
        'Iwo',
        'Obokun',
        'Odo-Otin',
        'Ola-Oluwa',
        'Olorunda',
        'Oriade',
        'Orolu',
        'Oshogbo',
    );

    protected static $oyoState = array(
        'Afijio',
        'Akinyele',
        'Atiba',
        'Atigbo',
        'Egbeda',
        'Ibadan Central',
        'Ibadan North',
        'Ibadan North West',
        'Ibadan South East',
        'Ibadan South West',
        'Ibarapa Central',
        'Ibarapa East',
        'Ibarapa North',
        'Ido',
        'Irepo',
        'Iseyin',
        'Itesiwaju',
        'Iwajowa',
        'Kajola',
        'Lagelu',
        'Ogbomosho North',
        'Ogbmosho South',
        'Ogo Oluwa',
        'Olorunsogo',
        'Oluyole',
        'Ona-Ara',
        'Orelope',
        'Ori Ire',
        'Oyo East',
        'Oyo West',
        'Saki East',
        'Saki West',
        'Surulere'
    );

    protected static $plateauState = array(
        'Barikin Ladi',
        'Bassa',
        'Bokkos',
        'Jos East',
        'Jos North',
        'Jos South',
        'Kanam',
        'Kanke',
        'Langtang North',
        'Langtang South',
        'Mangu',
        'Mikang',
        'Pankshin',
        'Qua\'an Pan',
        'Riyom',
        'Shendam',
        'Wase'
    );

    protected static $riversState = array(
        'Abua/Odual',
        'Ahoada East',
        'Ahoada West',
        'Akuku Toru',
        'Andoni',
        'Asari-Toru',
        'Bonny',
        'Degema',
        'Emohua',
        'Eleme',
        'Etche',
        'Gokana',
        'Ikwerre',
        'Khana',
        'Obia/Akpor',
        'Ogba/Egbema/Ndoni',
        'Ogu/Bolo',
        'Okrika',
        'Omumma',
        'Opobo/Nkoro',
        'Oyigbo',
        'Port-Harcourt',
        'Tai'
    );

    protected static $sokotoState = array(
        'Binji',
        'Bodinga',
        'Dange-shnsi',
        'Gada',
        'Goronyo',
        'Gudu',
        'Gawabawa',
        'Illela',
        'Isa',
        'Kware',
        'kebbe',
        'Rabah',
        'Sabon birni',
        'Shagari',
        'Silame',
        'Sokoto North',
        'Sokoto South',
        'Tambuwal',
        'Tangaza',
        'Tureta',
        'Wamako',
        'Wurno',
        'Yabo'
    );

    protected static $tarabaState = array(
        'Ardo-kola',
        'Bali',
        'Donga',
        'Gashaka',
        'Cassol',
        'Ibi',
        'Jalingo',
        'Karin-Lamido',
        'Kurmi',
        'Lau',
        'Sardauna',
        'Takum',
        'Ussa',
        'Wukari',
        'Yorro',
        'Zing'
    );

    protected static $yobeState = array(
        'Bade',
        'Bursari',
        'Damaturu',
        'Fika',
        'Fune',
        'Geidam',
        'Gujba',
        'Gulani',
        'Jakusko',
        'Karasuwa',
        'Karawa',
        'Machina',
        'Nangere',
        'Nguru Potiskum',
        'Tarmua',
        'Yunusari',
        'Yusufari'
    );

    protected static $zamfaraState = array(
        'Anka',
        'Bakura',
        'Birnin Magaji',
        'Bukkuyum',
        'Bungudu',
        'Gummi',
        'Gusau',
        'Kaura',
        'Namoda',
        'Maradun',
        'Maru',
        'Shinkafi',
        'Talata Mafara',
        'Tsafe',
        'Zurmi'
    );

    protected static $fctAbujaState = array(
        'Abaji',
        'Abuja Municipal',
        'Bwari',
        'Gwagwalada',
        'Kuje',
        'Kwali'
    );
}
